version: '2'

services:

  sync:
    image: derkades/cryptclone
    volumes: ['./data-sync:/data/documents:ro']
    command: sync
    environment:
      REMOTE_URL: http://server:80
      REMOTE_USER: test
      REMOTE_PASS: test2
      ENCRYPT_PASS: test
      BWLIMIT: "06:00,1M 01:00,2M"

  sync_interactive:
    image: derkades/cryptclone
    volumes: ['./data-sync:/data/documents:ro']
    command: sync
    tty: true
    environment:
      REMOTE_URL: http://server:80
      REMOTE_USER: test
      REMOTE_PASS: test2
      ENCRYPT_PASS: test
      INTERACTIVE_PROGRESS: 'true'

  restore:
    image: derkades/cryptclone
    volumes: ['./data-restore:/data']
    # To restore a subset of data, set RESTORE_DIR, e.g. RESTORE_DIR=documents/development
    command: restore
    environment:
      REMOTE_URL: http://server:80
      REMOTE_USER: test
      REMOTE_PASS: test2
      ENCRYPT_PASS: test

  server:
    image: derkades/webdav
    volumes: ['./data-server:/data']
    # ports: ['8080:80']
    environment:
      USERNAME: test
      PASSWORD: test2
